"""Criação da tabela de produtos

Revision ID: 00df134da508
Revises: 627b6e3ace46
Create Date: 2025-06-03 23:49:12.973804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00df134da508'
down_revision: Union[str, None] = '627b6e3ace46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=False),
    sa.Column('secao', sa.String(length=100), nullable=True),
    sa.Column('estoque_inicial', sa.Integer(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('imagens', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
