"""inserção da relação cliente x usuario

Revision ID: 106fa51c8425
Revises: fffed557cf94
Create Date: 2025-05-27 20:09:37.411714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106fa51c8425'
down_revision: Union[str, None] = 'fffed557cf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'usuario_id')
    # ### end Alembic commands ###
