"""Criação das tabelas users e clients

Revision ID: 627b6e3ace46
Revises: 
Create Date: 2025-06-02 11:18:43.968929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627b6e3ace46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('user_tipo', sa.String(length=1), nullable=False),
    sa.Column('user_senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_cpf', sa.String(length=14), nullable=False),
    sa.Column('client_email', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_cpf'),
    sa.UniqueConstraint('client_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('users')
    # ### end Alembic commands ###
