"""Atualização da tabela de produtos e users pra inserir o relacionamento

Revision ID: 6cb0e668e521
Revises: 00df134da508
Create Date: 2025-06-04 16:51:28.427042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb0e668e521'
down_revision: Union[str, None] = '00df134da508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'usuario_id')
    # ### end Alembic commands ###
