"""Update para tabelas

Revision ID: 8b4f5e227cf0
Revises: 
Create Date: 2025-06-25 21:56:41.419700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4f5e227cf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=False),
    sa.Column('secao', sa.String(length=100), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('imagens', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('user_tipo', sa.String(length=1), nullable=False),
    sa.Column('user_senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_cpf', sa.String(length=14), nullable=False),
    sa.Column('client_email', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_cpf'),
    sa.UniqueConstraint('client_email')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_products',
    sa.Column('orders_products_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('products_id', sa.Integer(), nullable=True),
    sa.Column('product_qntd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orders_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('orders_products_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_products')
    op.drop_table('orders')
    op.drop_table('clients')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
