"""inserindo dados no banco

Revision ID: ccf461a8f3a1
Revises: 203e35debe37
Create Date: 2025-05-24 13:12:04.313965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf461a8f3a1'
down_revision: Union[str, None] = '203e35debe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Inserindo dados diretamente
    op.execute(
        """
        INSERT INTO users (id, user_name, user_email, user_tipo, user_senha)
        VALUES 
        (1, 'Admin', 'admin@luestilo.com', 'A', '1234')
        """
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
